kind: secret
name: docker_username
get:
  path: secrets
  name: docker_username
---

kind: secret
name: docker_password
get:
  path: secrets
  name: docker_password
---




kind: pipeline
type: docker
name: default

clone:
  disable: true

environment:
  SERVER_NAME: cpctl
  GOPROXY: http://10.8.22.212:8081/repository/go-group/,direct
  GIT_NAME: gitlab.hycyg.com
  GIT_IP: 10.8.22.102

steps:
  - name: 拉取代码
    image: 10.8.22.212/drone/git:latest

  - name: 构建代码
    image: 10.8.22.212/paas/golang:1.20-fix-gitssh
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
      TARGET: $$(SERVER_NAME)
    commands:
#      - make build_server_linux
      - printenv