kind: secret
name: docker_username
get:
  path: secrets
  name: docker_username
---

kind: secret
name: docker_password
get:
  path: secrets
  name: docker_password
---




kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: 拉取代码
    image: 10.8.22.212/drone/git:latest
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - echo $USERNAME
      - echo $PASSWORD