kind: secret
name: docker_username
get:
  path: cpaas/data/docker
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: cpaas/data/docker
  name: docker_password
---
kind: secret
name: 122_ssh_password
get:
  path: cpaas/data/ssh
  name: 122_password
---



kind: pipeline
type: docker
name: default

trigger:
  branch:
    - dev
    - main
    - release/*
    - release*
    - hotfix/*
    - support/*
    - bugfix/*
  event:
    - push

platform:
  os: linux
  arch: amd64

clone:
  disable: true

environment:
  SERVER_NAME: cpctl
  GOPROXY: http://10.8.22.212:8081/repository/go-group/,direct
  GIT_NAME: gitlab.hycyg.com
  GIT_IP: 10.8.22.102
# 定义传递给 repo使用的环境变量
  PLUGIN_REPO: 10.8.22.212/paas/cpctl

steps:
  - name: 拉取代码
    image: 10.8.22.212/drone/git:latest

  - name: 构建代码
    image: 10.8.22.212/paas/golang:1.20-fix-gitssh
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - make build_server_linux
#      - printenv
    depends_on:
      - 拉取代码

  - name: 镜像推送
    image: plugins/docker
    settings:
      debug: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - ${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      insecure: true
      registry: 10.8.22.212
    depends_on:
      - 构建代码

  - name: 应用部署-docker-dev
    image: 10.8.22.212/dockerhub/appleboy/drone-ssh:1.7.0
    settings:
      host:
        - 10.8.22.250
      username: root
      password:
        from_secret: 122_ssh_password
      port: 22
      command_timeout: 30m
      script:
        - cpctl config update ${SERVER_NAME} version ${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
        - cpctl app restart ${SERVER_NAME}
    depends_on:
      - 镜像推送
    when:
        branch:
            - dev
            - hostfix/*
            - support/*
            - bugfix/*
        event:
            - push

  - name: 应用部署-docker-test
    image: 10.8.22.212/dockerhub/appleboy/drone-ssh:1.7.0
    environment:
      - SERVER_NAME: ${SERVER_NAME}
    settings:
      host:
        - 10.8.22.250
      username: root
      password:
        from_secret: 122_ssh_password
      port: 22
      command_timeout: 30m
      envs:
        - server_name
      script:
        - printenv
        - cpctl config update $SERVER_NAME version ${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
        - cpctl app restart ${SERVER_NAME}
    depends_on:
      - 镜像推送
    when:
      branch:
        - release/*
        - release*
        - main
      event:
        - push