kind: pipeline
type: docker
name: 发布


clone:
  disable: true


environment:
  NAME: cpctl
  OUTPUT_LINUX: cpctl.amd64.lin
  OUTPUT_WINDOWS: cpctl.amd64.exe
  OUTPUT_MAC: cpctl.amd64.mac
  CHANGELOG_TAG_OUTPUT: CHANGELOG.tag.md


steps:
  - name: 取码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    pull: always
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      outputs:
        - name: $${NAME}
          os: linux
          arch: amd64
        - name: $${OUTPUT_LINUX}
          os: linux
          arch: amd64
        - name: $${OUTPUT_WINDOWS}
          os: windows
          arch: amd64
        - name: $${OUTPUT_MAC}
          os: darwin
          arch: amd64

volumes:
  - name: go
    host:
      path: /var/lib/cache/go