kind: secret
name: docker_username
get:
  path: secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: secrets
  name: docker_password
---

kind: pipeline
type: docker
name: default

trigger:
  branch:
    - dev
    - main
    - release/*
    - release*
    - hotfix/*
    - support/*
    - bugfix/*
  event:
    - push

platform:
  os: linux
  arch: amd64

clone:
  disable: true

environment:
  SERVER_NAME: cpctl
  GOPROXY: http://10.8.22.212:8081/repository/go-group/,direct
  GIT_NAME: gitlab.hycyg.com
  GIT_IP: 10.8.22.102
# 定义传递给 repo使用的环境变量
  PLUGIN_REPO: 10.8.22.212/paas/cpctl

steps:
  - name: 拉取代码
    image: 10.8.22.212/drone/git:latest

  - name: 构建代码
    image: 10.8.22.212/paas/golang:1.20-fix-gitssh
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - make build_server_linux
      - printenv

  - name: 镜像推送
    image: plugins/docker
    settings:
      debug: true
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - ${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
      insecure: true
      registry: 10.8.22.212

  - name: 应用部署-docker
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.8.22.122
      username: root
      password:
        from_secret: 122_ssh_password
      port: 22
      command_timeout: 30m
      script:
        - cpctl config update ${SERVER_NAME} version ${DRONE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
        - cpctl app restart ${SERVER_NAME}
